@BASE_URL=http://localhost:3000
@DEVELOPER_ID=dev_eGWmxCzh0g8qJ0wQT2oCu


### list developers
GET {{BASE_URL}}/developers

### get developer
GET {{BASE_URL}}/developers/{{DEVELOPER_ID}}

### create developer
POST {{BASE_URL}}/developers
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@mail.com",
    "dateOfBirth": "1990-01-01"
}

### update developer
PATCH {{BASE_URL}}/developers/{{DEVELOPER_ID}}
Content-Type: application/json

{
    "email": "john@mail.com"
}

### delete developer
DELETE {{BASE_URL}}/developers/{{DEVELOPER_ID}}