@BASE_URL=http://localhost:3000
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAYWNtZS5jb20iLCJpYXQiOjE3MjczMjA0NDksImV4cCI6MTcyNzMyMDUwOX0.yS2m2ku3Kf00MHv-zgk6FuRIw-nDVAJ_VJ7ZqFOh83g
### public
GET {{BASE_URL}}/feature/public

### private
GET {{BASE_URL}}/feature/private
Authorization: Bearer {{TOKEN}}
