@BASE_URL=http://localhost:3000
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAYWNtZS5jb20iLCJzdWIiOiJlNzJhNDJiOS1iYzhhLTQ2YjgtYTI4Mi1lMGRhZWY4NjY2ZDciLCJyb2xlcyI6WyJhZG1pbiJdLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzI3Mzc4MDc1LCJleHAiOjE3MjczNzgxMzV9.N2bDN-xP-g9NpaWceB5X8Cm6JIagbQ6vloxcKaitvKs

### public
GET {{BASE_URL}}/feature/public

### private
GET {{BASE_URL}}/feature/private
Authorization: Bearer {{TOKEN}}

### admin
GET {{BASE_URL}}/feature/admin
Authorization: Bearer {{TOKEN}}
