@BASE_URL=http://localhost:3000
@REFRESH_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAYWNtZS5jb20iLCJzdWIiOiI5ZTc2YjYxYy0wYWJmLTQ2YTEtYjQ2OC1kZTNjYWI2NzExM2YiLCJyb2xlcyI6WyJhZG1pbiJdLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTcyNzM3ODQ0OCwiZXhwIjoxNzI3MzgyMDQ4fQ.dmZkyoEDKQIrE4hQtRbf09H3VZlO42VrgXCyxZJyyRM"

### signup
POST {{BASE_URL}}/auth/signup
Content-Type: application/json

{
  "email": "test@acme.com",
  "password": "test",
  "roles": ["admin"]
}

### signin
POST {{BASE_URL}}/auth/signin
Content-Type: application/json

{
  "email": "test@acme.com",
  "password": "test"
}

### refresh
POST {{BASE_URL}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": {{REFRESH_TOKEN}}
}